# Generated by Django 5.1.7 on 2025-04-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_alter_feedlike_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("twitter", "Twitter"), ("facebook", "Facebook")],
                        max_length=10,
                    ),
                ),
                ("post_id", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
